### ISSUE TITLE
Another events. Repair. Damage.

### ISSUE THREAD

**Issue by loderain** [RenCloud/scs-sdk-plugin#100]
Hello, i see that there aren't exist events at repair and damage moments. It would be fantastic to implements methods to be triggered when truck is repaired or when truck receive damage. Thx for your work.

**Comment by RenCloud** [comment]
Hey, there is no such a game event defined in the SDK. So it would not make a big difference to implement it outside the plugin or inside. At the end, both would just create an event based on the damage values. 

Therefore, I think it would be better placed outside the plugin, so in your own code. So you can also fine tune at which level damage fires the event and when not. Some damage is inflicted while driving, but that is so small you probably will not see most of it in the game unless you are driving a very long distance.

Also, changing truck or profile will be not completely handled, similar to other values when a change happens.

**Comment by RenCloud** [comment]
Closed. Currently, not planned and inactive. Can be done more controlled within the project which use the library instead of putting the feature in the library.
