### ISSUE TITLE
Report Coinsurance in American Truck Simulator

### ISSUE THREAD

**Issue by orestescm76** [RenCloud/scs-sdk-plugin#101]
The Dll does not report the coinsurance % in American Truck Simulator. It would be useful for the user to see in real time the value in order to reduce it.
Maybe it is not available on the SDK but might as well open this issue.

**Comment by RenCloud** [comment]
Currently all values that the sdk provide are available through the dll.


However, which value do you exactly mean with coinsurance %?

**Comment by orestescm76** [comment]
This is the value: 
![image](https://user-images.githubusercontent.com/21990645/167360627-43d5d851-e561-46ab-848d-71ef27ee92ab.png)
Supposedly, it increases with the more you crash and decreases if you don't crash your truck.

**Comment by RenCloud** [comment]
Indeed that could be useful to have, but currently it is not available. May in a future release of the sdk
