### ISSUE TITLE
Question Regarding Unit of Measurement

### ISSUE THREAD

**Issue by arinanto** [RenCloud/scs-sdk-plugin#102]
Is there any documentation about units, the speed for instance is in m/s but revolution is in rpm. Seems to be mix between mostly used and SI measurement and I can't find any documentation about it even in SCS SDK.

**Comment by RenCloud** [comment]
Within the scs sdk source code are some hints about the used units, but not more than a specific value use m/s.

A bit documentation, not directly specific to the sdk but more modding I guess, is available in the wiki https://modding.scssoft.com/wiki/Documentation/Engine/Units. However, there seems to be no information about speed or similar. So source of the sdk seems to be all. At least I do not know any other documentation.
