### ISSUE TITLE
New SDK Version

### ISSUE THREAD

**Issue by RenCloud** [RenCloud/scs-sdk-plugin#103]
New SDK Version 1.14 was added as open beta.
Seems to provide some information for multiplayer, fixed some stuff and allows creating input devices
`added multiplayer time offset and trailer body wear channel, fixed trailer chassis wear channel`

**Comment by YeapGuy** [comment]
It's out of beta now 👀

**Comment by RenCloud** [comment]
Indeed. I will make a small release for that. 

There are some new values and other features, but I will just add the new values. 

If there is interest for the input devices that can be created, please open a new issue and I will take a look at that earlier. Currently it has no priority for me and needs some work.

**Comment by RenCloud** [comment]
SDK Version was updated in the last V 1.12 release
