### ISSUE TITLE
Steam ID Fetching

### ISSUE THREAD

**Issue by InsanoDeath3** [RenCloud/scs-sdk-plugin#104]
This is the feature that we can get the steam ID details from which the user has launched the game. This would be a great addon for this plugin

**Comment by ndelta0** [comment]
I think that goes out of scope of this project, as it is solely focused on retrieving the information from the game and enabling it to be processed outside of the scope of the game process (i.e. a background system process/service or logger).

**Comment by RenCloud** [comment]
I understand that, but this would result in additional dependencies for information that are not part of the game.  So currently I do not see place for that in this project.
