### ISSUE TITLE
Telemetry server sdk update

### ISSUE THREAD

**Issue by Klaax** [RenCloud/scs-sdk-plugin#107]
Hi, I want to update Funbit's telemetry server to work with your latest sdk, can you give me some guidance on how to do it? I would be very grateful.

**Comment by RenCloud** [comment]
Hi, the original Funbit's server uses an old modified version of the nlhans plugin. This gets the data from the game and write it in the memory, so the server can access it and share it as JSON to its clients.

For most of the values, the progress is straight forward to the existing ones. Basically just the `registerChannel` function and adding the value to the `ets2TelemetryMap_s` struct. After that, you would have to update the server to also read the new values. You can find the names in the header files of the SDK. 


However, there are some forks that use my plugin. Probably some that may use the 1.11 release. Then you would only need to update this plugin and modify the mapping on the server side with small changes.

**Comment by RenCloud** [comment]
Closed due to inactivity.
