### ISSUE TITLE
Improve versioning

### ISSUE THREAD

**Issue by kniffen** [RenCloud/scs-sdk-plugin#108]
Currently the plugin version number provided by the plugin itself is just the minor
for example `11`
So there is no way of distinguishing between say plugin version `1.11` and `1.11.1`, it gives `11` for both

As `1.11.1` also had some braking changes as it added new values and moved some offsets,
it may also be that it should have been a `1.12` release?

**Comment by RenCloud** [comment]
Indeed, the versioning is not every time on point. I messed that up a few times in the past, too. 

Just adding new values, I think, is not directly need a new minor version. You can update both sides separately without "problems". Offset changes need updates on both sides. 

The last should be 1.12 indeed. Wrong thinking of me. The big update I planned to be the 1.12 should probably the 2.0 upgrade.

May I should change the current to 1.12 making it more clear, that there are changes on the offset.

**Comment by RenCloud** [comment]
Updated version to 1.12. No other changes than the version in this release.
