### ISSUE TITLE
Telemetry Plugin not loading

### ISSUE THREAD

**Issue by UKNickyD** [RenCloud/scs-sdk-plugin#109]
Hi, 

I have extracted scs-telemetry and scs_sdk, ran the solution within scs-telemetry and placed the resulting .dll in the ets2 plugins folder. However it doesn't seem to be loading the plugin, as I get no popup telling about the sdk access, and any other code I'm writing for my end just isnt working. Am I doing something wrong when building the plugin?

Thanks

**Comment by RenCloud** [comment]
Hey, first could open the in-game terminal to see if there is some message about the telemetry, maybe that there was an error or nothing. 

If you do not see a message, you can enter the command 
`sdk reload` and see if there is a direct response to that. 
If not, the dll is either placed in the wrong location or it is the wrong dll.

May you also skipped the sdk dialog with pressing `esc` after the loading screen by accident.


If there are no information in the in-game terminal, or you did not skip the dialog, please provide some more information. Then I can provide more help.

OS, Game Version, building with Visual Studio or cli ...

**Comment by RenCloud** [comment]
Clothed due to inactivity.
