### ISSUE TITLE
Activated Mods Data

### ISSUE THREAD

**Issue by InsanoDeath3** [RenCloud/scs-sdk-plugin#111]
it is simple, getting game activated mods data so that we can know which mods are used and current time

**Comment by MJRLegends** [comment]
Looking at the Telemetry SDK from SCS this kinda of data isnt provided through the SDK systems

**Comment by InsanoDeath3** [comment]
so is there any way we can get it?

**Comment by jorensanbar** [comment]
Create your own program that access to the data of profile (saves) and extract the info.

**Comment by InsanoDeath3** [comment]
Also one more is that possible to add top speed in the telemetry data while doing a job?

**Comment by jorensanbar** [comment]
You have to do that with your own programming, when the telemetry gives you the current speed, you save your variable that stores the maximum recorded.

**Comment by InsanoDeath3** [comment]
Thank You
