### ISSUE TITLE
Getting Way Points marks data

### ISSUE THREAD

**Issue by InsanoDeath3** [RenCloud/scs-sdk-plugin#113]
is it possible to get the destination or way point coordinates from the game.

**Comment by MJRLegends** [comment]
Looking at the games scs sdk, none of this data is available

**Comment by InsanoDeath3** [comment]
isnt there some way for this?

**Comment by MJRLegends** [comment]
Not sure if the sdk by the game devs dont have it then its very hard to obtain the information and would defo require methods that this project doesnt touch

**Comment by InsanoDeath3** [comment]
I have one more question is there any predefined way to send in game text message and notification?

**Comment by MJRLegends** [comment]
Nope
