### ISSUE TITLE
Multiplayer Time Offset is not transferred to SimHub or cannot be found there.

### ISSUE THREAD

**Issue by senoyches** [RenCloud/scs-sdk-plugin#114]
**Describe the bug**
This is not really a bug, much more a question, but I do not know how to contact you manually, so here is the question:

I use the telemetry data with SimHub, because I wanted to query an important value for me namely the "Multiplayer Time Offset", but I can not find it there, no matter what I enter, I wanted to ask if you can help me how I can find it?

Because when I start your DemoApp, the value is displayed, so it seems the dll that I have moved into the ETS/ATS directory also transmit.

**To Reproduce**
Open SimHub and search for the value above

**Expected behavior**
Can you help me how can I solve this little problem?

**Screenshots**

**Desktop (please complete the following information):**
 Windows 10
 SimHub 8.3.7
Last Version Nov 2022 1.12

**Additional context**
maybe it is a problem in the transmission to Simhub, but unfortunately it is beyond my knowledge, so I will ask here.

**Comment by RenCloud** [comment]
Based on the documentation I found, Simhub only supports Funbits and nhlans version. This fork adds a lot of fields and changes the structure so without changes on the Simhub site this plugin won't work as also described here https://github.com/SHWotever/SimHub/wiki/SimHub-Basics----Games-config-and-troubleshooting#ets2--ats with the repository information here
https://github.com/SHWotever/SimHub/wiki#special-thanks-
