### ISSUE TITLE
Job didn't finish if you set directly a new route 

### ISSUE THREAD

**Issue by RenCloud** [RenCloud/scs-sdk-plugin#20]
think about a better way to handle that ? 

may compare cities

**Comment by RenCloud** [comment]
every think doesn't change sadly

but still for no ownership i should change something

for ownership i have to try a few things

**Comment by danielalmeida1481** [comment]
Maybe check if the new distance route is bigger than the route before the game gets paused

**Comment by danielalmeida1481** [comment]
I don't know if i'm right but if you cancel a job or you're not doing any job I think that the cargo info is empty so instead of updating cargo info when the trailer is detached update it when something change like the cargo name

**Comment by RenCloud** [comment]
so you want that when you detached the trailer the informations are still there for the trailer?

and first when a value change it should change the value?

**Comment by danielalmeida1481** [comment]
It can't be a random value I think that the most correct value to check is the cargo name. But basically yes that's what I'm suggesting

**Comment by RenCloud** [comment]
With changing the handling of the Configuration values, i changed also the way the trailer values are handled.

If the game says, there is a trailer connected with you(on job, trailer ownership) it doesn't matter if you detached it or it is attached. The values are displayed and refreshed if the game says so.

If the game says, there is no trailer connected to you, than all values are reseted.

To get a clear state, there is also an Flag and 2 possible events (based on the flag: trailer connected and trailer disconnected) to determine if a trailer is connected or not. 

I hope that way is ok for you kind of application.
