### ISSUE TITLE
Wrong shared memory map name in documentation

### ISSUE THREAD

**Issue by kniffen** [RenCloud/scs-sdk-plugin#41]
In [README.md](https://github.com/RenCloud/scs-sdk-plugin/blob/master/README.md) and the [documentation page](https://rencloud.github.io/scs-sdk-plugin/) it says the shared memory map name is **Local\SCSTelemetry** when in actual fact it's **Local\SimTelemetrySCS**

**Comment by RenCloud** [comment]
Indeed ... this should not happen. I will fix that
