### ISSUE TITLE
hi, can you help me with the code ?

### ISSUE THREAD

**Issue by neonil123** [RenCloud/scs-sdk-plugin#43]
i need a simple program (just to output data in the console)
but i dont know how to read data from the object.
this is my code.
can you give me an example of how to get data (create propper object and use it)

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Ets2SdkClient;

namespace fdggdf
{

class Program
{
//Ets2SdkClient.Ets2SdkTelemetry Telemetry = new Ets2SdkClient.Ets2SdkTelemetry();
Ets2SdkClient.Ets2Telemetry._Physics a = new Ets2SdkClient.Ets2Telemetry._Physics();
Ets2SdkClient.Ets2Telemetry._Drivetrain b = new Ets2SdkClient.Ets2Telemetry._Drivetrain() ;

static void Main(string[] args)
{
    Program P = new Program();

   while (true)
    { 
    float m = P.a.AccelerationZ;
    float z = P.b.EngineRpmMax;
    Console.WriteLine(m);
    Console.WriteLine(z);
    }

}
}

**Comment by danielalmeida1481** [comment]
You need to do this:


public SCSSdkTelemetry Telemetry;


public SCSSdkClientDemo() {

InitializeComponent();

Telemetry = new SCSSdkTelemetry();

Telemetry.Data += Telemetry_Data;

if (Telemetry.Error != null) {

// Error connection to the memory map
}



}


private void Telemetry_Data(SCSTelemetry data, bool updated) {

try {

if (InvokeRequired) {

Invoke(new TelemetryData(Telemetry_Data), data, updated);

return;

}

// Here you receive the data
} catch (Exception ex) {


}

}

**Comment by neonil123** [comment]
hi i want to know if i have to use inheritance because i have some errors .
or i have to declare another object.
the  program didn't find some methods.
Ps. Sorry but i don't know C#




![Annotazione 2019-08-10 173107](https://user-images.githubusercontent.com/38853538/62823014-be134a80-bb94-11e9-9a34-0cb21cd24fc5.png)
![Annotazione 2019-08-10 173055](https://user-images.githubusercontent.com/38853538/62823015-be134a80-bb94-11e9-98bb-03328645faaf.png)

**Comment by danielalmeida1481** [comment]
Oops my bad
It's giving you errors because I'm instanciating the object on a static method

**Comment by danielalmeida1481** [comment]
Copy the object to the static method and it should work
P.s: remove the initializeComponent

**Comment by neonil123** [comment]
i have some problems with invokeRequired

![Annotazione 2019-08-10 175417](https://user-images.githubusercontent.com/38853538/62823250-fe27fc80-bb97-11e9-8933-eca6c8cac3b6.png)
![Annotazione 2019-08-10 175403](https://user-images.githubusercontent.com/38853538/62823251-fe27fc80-bb97-11e9-98cc-b530d7247ceb.png)

**Comment by RenCloud** [comment]
`InvokeRequired` is a object of an Windows Forms Control object.
When you write a console program it doesn't exist.


Also the plugin works with Events, because the data is updated automatically.  That is also possible to handle without a GUI, but you need something that won't close the program in the time:

you could try

```C#
static void Main(string[] args) {
    SCSSdkTelemetry Telemetry = new SCSSdkTelemetry();
    Telemetry.Data += Telemetry_Data;
    if (Telemetry.Error != null) {
        // Error connection to the memory map
    }
   // do not close the program until `q` was typed 
   while (Console.ReadKey(true).KeyChar == 'q'){
                // Quit program        
    }
}


private void Telemetry_Data(SCSTelemetry data, bool updated) {
    try {
        // acces data here wit `data`
 
    } catch (Exception ex) {
    }
}

```

**Comment by RenCloud** [comment]
I guess that answered your question so i will close that issue. If not you can reopen this issue or if it a new one open a new one. Thanks.
