### ISSUE TITLE
Telemetry.Data event not firing

### ISSUE THREAD

**Issue by veso266** [RenCloud/scs-sdk-plugin#56]
posting this here as I am afraid nobody will see it in the original repo :smile: 

Hi there
for some weird reason I am not able to get any data out of ETS2 with my Console app while your Client Demo works fine

I referenced Ets2SdkClient.dll (ets2sdkclient-project), copied the ets2-telemetry.dll into gamedir/plugins forlder

but then when trying to get even some basic info like this:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Ets2SdkClient;

namespace Ets2_Timer
{
    class Game
    {
        public static Ets2SdkTelemetry Telemetry;
        public Game()
        {
            //Start telemetry grabbing:
            Telemetry = new Ets2SdkTelemetry(20);
            Telemetry.Data += Telemetry_Data;
        }
        private void Telemetry_Data(Ets2Telemetry data, bool updated)
        {
            if (Telemetry.Error == null)
            {
                Console.Write("General info:\r\n SDK Version: " + data.Version.SdkPlugin + "\r\n Reported game Version: " +
                             data.Version.Ets2Major + "." + data.Version.Ets2Minor + "\r\n\r\nTruck: " + data.Truck + " (" + data.TruckId + ")\r\nManufacturer: " + data.Manufacturer + "(" + data.ManufacturerId + ")" +
                             "\r\nGame Timestamp: " + data.Time + "\r\nPaused? " + data.Paused);
            }
        }
    }
    class Program
    {
        
        static void Main(string[] args)
        {
            Game gm = new Game();
            Console.ReadLine();
        }

        
    }
}
```

nothing is ever fired Telemetry_Data event handler is never called and thus no output on console, also I am not sure how would I be able to get Games internal time continuously (Telemetry_Data should be fired all the time or if you specify it like this 
```csharp 
elemetry = new Ets2SdkTelemetry(250); 
```
 in 250ms intervals)

not sure what I am doing wrong
here is the project
[Ets2-Timer.zip](https://github.com/nlhans/ets2-sdk-plugin/files/3936604/Ets2-Timer.zip)

**Comment by RenCloud** [comment]
Hi veso,
i'm not quite sure why, but it seems that the ets2SdkClient is throwing `TypeLoadException` when you want to use it that way. 
Well, i am not aware of the reason. So you could try to fix that problem on your own or switch to this Repository. It seems that i make some changes to the code base in such a way that it is possible to use it that way.

**Comment by veso266** [comment]
switched to your repo and it works now :smile: 
![slika](https://user-images.githubusercontent.com/6347325/70852171-9fa0c100-1e9e-11ea-9165-cf4603d0229a.png)

BTW: How would I get ingame time? (timestamp (data.Timestamp) is not the right time as it starts counting from 0)

**Comment by RenCloud** [comment]
Great 👍 

`data.CommonValues.GameTime` contains the in-game time. It is a `Time` Object.
If you want a DateTime object use `data.CommonValues.GameTime.Date`.

**Comment by veso266** [comment]
Did all this maddness and got my time :smile: 
```c#
string[] uraArr = data.CommonValues.GameTime.Date.ToUniversalTime().ToString().Split(' ')[1].Split(':');
string time = string.Join(":", uraArr.Reverse().Skip(1).Reverse());
```

**Comment by RenCloud** [comment]
That's a lot of code for that.
You could try  [DateTime.ToString()](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.tostring?view=netframework-4.8) or use one of the properties of a DateTime object [DateTime Struct](https://docs.microsoft.com/en-us/dotnet/api/system.datetime?view=netframework-4.8#properties).
