### ISSUE TITLE
DLL in Demo Projekt

### ISSUE THREAD

**Issue by thommy1972deNeu** [RenCloud/scs-sdk-plugin#59]
Could someone explain how to compile the SCSSdkClient.dll file? I received a dll, but cannot insert it into the project because of an error message.

**Comment by RenCloud** [comment]
Simplest way would work with Visual Studio and select Build on the SCSSdkClient project.

Which error message did you get?

**Comment by thommy1972deNeu** [comment]
I have your Client Demo with the SCSSdkClient.dll. But when i start the Game, the Client do nothing. I need the dll for the Game -> plugins Folder

**Comment by RenCloud** [comment]
If you build yourself you need to build the scs-telemetry project. The dll is than in the Release dir of SCS-Client. Path should be something like `...\scs-client\C#\SCSSdkClient\Release`.

**Comment by thommy1972deNeu** [comment]
Warum reden wir English, du bist doch in Hannover ???
Yes, we make it so and its work for me. Many new Features in this Release. You Work on Updates for this Repo ?

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by RenCloud** [comment]
Deutsch geht auch. Du hattest nur auf englisch angefangen und es ist üblich auf Github und ähnlichem auf englisch zu schreiben. 

That's great. Yes i work on updates for this repo.

**Comment by thommy1972deNeu** [comment]
Ja das stimmt, aber mein Englisch ist total Bescheiden und ich schreibe da bestimmt nur Mist zusammen 😊 

Ja wir haben das mit der Telemetrie soweit hinbekommen. Wir sind ein kleines Team und machen einen Client für ETS. ATS ging mit unserer alten Tele nicht. Deswegen sind wir im Moment von dem Funktionsumfang der neuen Telemetrie etwas geplättet und müssen jetzt ziemlich viel umschreiben. 

Würde das gerne in WPF umschreiben, aber derzeit müssen wir schauen dass es erstmal in WindowsForms geht.

Wir haben unser Tool auch auf Github, wenn du Interesse hast, kann dir der Projektleiter die Einladung senden.

 

https://vtc.northwestvideo.de/

 

https://github.com/TheNorthWestMediaGroup/VTCManager-Client

 

 

 


  <https://ujpl9g.am.files.1drv.com/y4mOg-266s4DbuqRMRHu56BCT6kmHHWHj4vPZ7A-J1IV06rvzLMi0t_HT29Ur4sTBLKSZzdtP6YUEJpqWyfECWhPYOsFtkIhGk7AJ5Y7VEfXxo_l1cypPu1FMQR5JWFS2y4rtfQZwJSpKS_rWm1S25wxZ2PjW58ejDKOQktnJg1D9dlSYrS9RaunS626C_X66ytjX1NFmrYcYqtrN9fgcR7bw?widt> 


Thomas Blasius

	

phone: +49 6332 896 31 31


email: edv.blasius@gmail.com


Europaring 47, 66482 Zweibrücken 
 <https://goo.gl/maps/xo7WcFqBJeUWJ6V66> ✈ Google Maps 

	

 <https://www.facebook.com/blasiusthomas?ref=bookmarks>   


The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

 

 

Von: Jonas Fabisiak <notifications@github.com> 
Gesendet: Mittwoch, 11. März 2020 09:32
An: RenCloud/scs-sdk-plugin <scs-sdk-plugin@noreply.github.com>
Cc: Thommy <info@zwpc.de>; Author <author@noreply.github.com>
Betreff: Re: [RenCloud/scs-sdk-plugin] DLL in Demo Projekt (#59)

 

Deutsch geht auch. Du hattest nur auf englisch angefangen und es ist üblich auf Github und ähnlichem auf englisch zu schreiben.

That's great. Yes i work on updates for this repo.

**Comment by RenCloud** [comment]
Klingt auf jedenfall sehr interessant. Mit VTC und TruckersMP habe ich mich noch nicht viel beschäftig. Aber ich würd mir das gerne mal ansehen.  

ATS sollte funktionieren und mit Hilfe eines Enums unterschieden werden können. WPF habe ich mit der Bibliothek noch nicht getestet sollte, aber auch damit laufen.

**Comment by thommy1972deNeu** [comment]
Einladung ist raus.

ATS geht, aber da es in unserer alten Tele noch nicht implementiert war, haben wir bislang noch nicht Testen können. 

 

Ich muss leider zur Arbeit. Wenn du Fragen hast, einfach melden. 

 

 

 

Von: Jonas Fabisiak <notifications@github.com> 
Gesendet: Mittwoch, 11. März 2020 10:36
An: RenCloud/scs-sdk-plugin <scs-sdk-plugin@noreply.github.com>
Cc: Thommy <info@zwpc.de>; Author <author@noreply.github.com>
Betreff: Re: [RenCloud/scs-sdk-plugin] DLL in Demo Projekt (#59)

 

Klingt auf jedenfall sehr interessant. Mit VTC und TruckersMP habe ich mich noch nicht viel beschäftig. Aber ich würd mir das gerne mal ansehen.

ATS sollte funktionieren und mit Hilfe eines Enums unterschieden werden können. WPF habe ich mit der Bibliothek noch nicht getestet sollte, aber auch damit laufen.

**Comment by thommy1972deNeu** [comment]
Nochmal ich 😊

Könntest du mir kurz sagen, wie ich den Betrag von Tollgate und Refuel erhalte ?

Für Tollgate habe ich data.GamePlay.TollgateEvent.PayAmount; (-> ergibt immer 0)

Und Refuel finde ich garnichts.

In der Doku ist Gme Values->SpecialEvents->Refuel Start / End / Payed aber das erhalte ich in VS nicht.

 

 


  <https://ujpl9g.am.files.1drv.com/y4mOg-266s4DbuqRMRHu56BCT6kmHHWHj4vPZ7A-J1IV06rvzLMi0t_HT29Ur4sTBLKSZzdtP6YUEJpqWyfECWhPYOsFtkIhGk7AJ5Y7VEfXxo_l1cypPu1FMQR5JWFS2y4rtfQZwJSpKS_rWm1S25wxZ2PjW58ejDKOQktnJg1D9dlSYrS9RaunS626C_X66ytjX1NFmrYcYqtrN9fgcR7bw?widt> 


Thomas Blasius


Kleinunternehmer


phone: +49 6332 896 31 31


email: edv.blasius@gmail.com


Europaring 47, 66482 Zweibrücken 
 <https://goo.gl/maps/xo7WcFqBJeUWJ6V66> ✈ Google Maps 

	

 <https://www.facebook.com/blasiusthomas?ref=bookmarks>   


The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

**Comment by RenCloud** [comment]
Die sollten dort auch zu finden sein:
[GamePlayEvents.cs](https://github.com/RenCloud/scs-sdk-plugin/blob/master/scs-client/C%23/SCSSdkClient/Object/SCSTelemetry.GamePlayEvents.cs)

Zu Tollgate -> es wird nur ausgelöst wenn du beim durchfahren auch etwas Zahlst. D.h. du must in einem eigenen Truck sitzen. Bei anderen wird das Event meine ich nicht ausgelöst.

**Comment by thommy1972deNeu** [comment]
Noch eine kurze Frage, dann Nerv ich auch nur noch 1x die Woche 😊 

Gibt es für die Touren vielleicht einen fixe ID ? 

Wir versuchen das Problem zu lösen, wenn jemand den Client beim Fahren schließt. Dann müssten wir prüfen, ob die Tour die selbe wie vorher ist oder ob es eine andere ist.

Ich dachte daran eine ID in die Registry zu schreiben allerdings finde ich keine Fixe ID der Tour.

Gibt es sowas ?

 

 

 


  <https://ujpl9g.am.files.1drv.com/y4mOg-266s4DbuqRMRHu56BCT6kmHHWHj4vPZ7A-J1IV06rvzLMi0t_HT29Ur4sTBLKSZzdtP6YUEJpqWyfECWhPYOsFtkIhGk7AJ5Y7VEfXxo_l1cypPu1FMQR5JWFS2y4rtfQZwJSpKS_rWm1S25wxZ2PjW58ejDKOQktnJg1D9dlSYrS9RaunS626C_X66ytjX1NFmrYcYqtrN9fgcR7bw?widt> 


Thomas Blasius


Kleinunternehmer


phone: +49 6332 896 31 31


email: edv.blasius@gmail.com


Europaring 47, 66482 Zweibrücken 
 <https://goo.gl/maps/xo7WcFqBJeUWJ6V66> ✈ Google Maps 

	

 <https://www.facebook.com/blasiusthomas?ref=bookmarks>   


The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

 

 

Von: Jonas Fabisiak <notifications@github.com> 
Gesendet: Montag, 16. März 2020 15:42
An: RenCloud/scs-sdk-plugin <scs-sdk-plugin@noreply.github.com>
Cc: Thommy <info@zwpc.de>; Author <author@noreply.github.com>
Betreff: Re: [RenCloud/scs-sdk-plugin] DLL in Demo Projekt (#59)

 

Die sollten dort auch zu finden sein:
GamePlayEvents.cs <https://github.com/RenCloud/scs-sdk-plugin/blob/master/scs-client/C%23/SCSSdkClient/Object/SCSTelemetry.GamePlayEvents.cs> 

Zu Tollgate -> es wird nur ausgelöst wenn du beim durchfahren auch etwas Zahlst. D.h. du must in einem eigenen Truck sitzen. Bei anderen wird das Event meine ich nicht ausgelöst.

**Comment by RenCloud** [comment]
Alles gut bisher.

Ich kenne das Problem. So eine ID brauchte ich auch schon mal. Aber ohne das Kombinieren von anderen Eigenschaften wird das wohl nichts. Die SDK liefert bislang keine.
