### ISSUE TITLE
Support für Eigene trailer

### ISSUE THREAD

**Issue by thommy1972deNeu** [RenCloud/scs-sdk-plugin#62]
Gibt es eine Value für eigene Trailer ?
Oder kann man irgendwie herausfinden, ob ein eigener Trailer angehangen ist ? 
Die Jobdaten werden bei eigenen Trailern nur sporadisch angezeigt.

**Comment by RenCloud** [comment]
Es gibt keine Value, die dir sagt das es ein eigener Trailer ist. Es könnte sein (ich habe jetzt nicht viel ausprobiert), dass die Trailer Marke oder Trailer ID unterschiedlich ist. Müsste man verschiedene Trailer testen.

Ansonsten gibt es die Value CargoLoaded. Die ist soweit ich weiß, nur während eines Job true, da sonst nie Cargo geladen ist.

Welche Werte? Bei mir ist alles da.

**Comment by thommy1972deNeu** [comment]
Habe ein wenig Ausprobiert und bei mir geht es zumindest auch mit eigenem Trailer. Nur bei mir geht irgendwie alles, nur bei anderen nicht :-) 
CargoLoaded ist gut !!

Danke !
