### ISSUE TITLE
Rename the SCSSdkClient and/or sc-telemetry.dll

### ISSUE THREAD

**Issue by thommy1972deNeu** [RenCloud/scs-sdk-plugin#63]
How to rename the DLL files? Simply renaming the file itself won't do much good. In the meantime, some tools have the same dll and these probably don't really work together.

**Comment by RenCloud** [comment]
When the tools use the same version of the same plugin then there should be no problem at all -> only use one .dll in the plugin dir and it should work.



When you use more and the version is not the same or they use some forks or own version of the sdk then you need to change the shared memory location. 

So you need to change it in the c++ files and in the c# plugin code. Use a unique may containing your project/app name should avoid problems like that.

See c++ [here ](https://github.com/RenCloud/scs-sdk-plugin/blob/3a3bc4084a0b1bf3df61265df95f944b42a0489e/scs-telemetry/inc/scs-telemetry-common.hpp#L25)
and C# [here ](https://github.com/RenCloud/scs-sdk-plugin/blob/3a3bc4084a0b1bf3df61265df95f944b42a0489e/scs-client/C%23/SCSSdkClient/SCSSdkTelemetry.cs#L14)
