### ISSUE TITLE
Differential Lock indicator

### ISSUE THREAD

**Issue by KRtekTM** [RenCloud/scs-sdk-plugin#65]
I'm building instrument cluster for ETS2 using this library. I can't find the right value in the offered telemetry object to get the indicator of locked differentials.

Is there any way to get this value (as it's implemented and I'm just searching badly) or this is something like GPS route (not offered by SCS SDK)?

Big thanks for the work already done!

**Comment by thommy1972deNeu** [comment]
I found one in  the Readme @TruckValues->Constants->MotorValues->Differential Ration

**Comment by GonzoG** [comment]
> I found one in the Readme @TruckValues->Constants->MotorValues->Differential Ration

It's differential gear ratio.

**Comment by killerjoey55** [comment]
The `DifferentialRation` seems to be a static property of the truck chassis, not seeing any change in the value when diff lock is enabled / disabled.

**Comment by RenCloud** [comment]
Differential Lock was added with the new sdk version. Currently in dev-branch, because it is not finished and the game version 1.41 is currently in public beta.
