### ISSUE TITLE
data.JobValues.DeliveryTime.Value

### ISSUE THREAD

**Issue by thommy1972deNeu** [RenCloud/scs-sdk-plugin#66]
Ich erhalte aus der Variable wohl einen Timestamp. Leider kann ich diesen nicht Recht zuordnen, da es kein "normaler" Timestamp sein kann.
Wie erhalte ich den Wert der Restliche Lieferzeit ? (Taste -> F6 'Restzeit')
(Nicht der Navigations-Fahrzeit)

**Comment by RenCloud** [comment]
Value ist der Timestamp vom Game. Also In-Game Minuten. Über DeliveryTime.DateTime müstest du ein DateTime object bekommen mit dem In-Game Datum.

RemainingDeliveryTime in data.jobValues 
`  Remaining in-game time until the job delivery window close` sollte der Wert sein den du suchst.

**Comment by thommy1972deNeu** [comment]
Mit data.JobValues.RemainingDeliveryTime.Value bekomme ich immer 0 als int, obwohl ich noch 14 Std Restzeit habe ?

**Comment by thommy1972deNeu** [comment]
TimeSpan zeit = TimeSpan.FromSeconds(data.JobValues.DeliveryTime.Value); 
lbl_Time_Remain.Text = zeit.Days + " Tag(e)" + zeit.Hours + " Stunde(n) " + zeit.Minutes + " Minute(n) " + zeit.Seconds + " Sekunde(n)";
                        
Gibt mir 162 Tage, 18 Stunden, 51 Minuten und 10 Sekunden... Kann auch nicht sein :-(

**Comment by RenCloud** [comment]
Das sollte so nicht sein. 

Könnte sein. Das Spiel zählt von Tag 1.1.0001 an. Wenn dein Profil nicht so alt ist könnte das passen.
Delivery gibt ja den Moment an und nicht die restliche Zeit.

**Comment by thommy1972deNeu** [comment]
Meine reine Spielzeit liegt laut SCS bei 705 Stunden was umgerechnet nicht gnz 1 Monat wäre. Mein Profil ist laut meiner Profilseite 9958 Tage und 16 Stunden alt, also Umgerechnet 27 Jahre und paar Stunden.
Demnach hab ich mir das Profil am irgendwann im Mai 1993 angelegt. Das Spiel kam zwar erst 2012 auf den Markt und ich habe mir das Spiel erst 2013 gekauft, aber vielleicht war ich ja schon Alpha Tester. *ROFL*
Ganz ehrlich, keine Ahnung wo die die Zahlen hernehmen aber irgenwas passt da nicht ganz. 
Also den Wert den das Game im Fenster "F6" als Restzeit ngibt, bekommt man nicht direkt ausgegeben und muss berechnet werden ?

**Comment by RenCloud** [comment]
Ok dann passt alles.

`Value` ist in Minuten und nicht Sekunden. Du must also beim nehmen von `TimeSpan.FromSeconds()`  die Value * 60 nehmen. Dann bekommst du ebenfalls einen Wert um die 99xx. 

Das Alter auf deinem Profil ist keine Echtzeit, sondern ist die `In_Game Zeit` -> diese ist ~5 mal so schnell je nachdem wo du bist (Stadt oder Autobahn) und Schlafen, Fähren und Zugfahrt verändern den Wert. (Schlafen um die +6 Stunden, Fähre und Zugfahr je nach länge der Fahr).

Eigentlich sollte der Wert in `RemainingDeliveryTime ` zufinden sein. Dieser wird eigentlich über die aktuelle In-Game Zeit ( Tag 9958 ) und den Wert von `DeliveryTime` (im Normalfall etwas größeres als die aktuelle Zeit) berechnet.
Rechnung ist dann `DeliveryTime - GameTime = RemainingDeliveryTime`.

Allerdings mache ich aktuell einen Fehler, wodurch `RemainingDeliveryTime` nicht berechnet wird. Das fixe ich gleich.
