### ISSUE TITLE
Q: Where to raise feature requests to SCS for additional data to be exposed?

### ISSUE THREAD

**Issue by mwerle** [RenCloud/scs-sdk-plugin#67]
Sorry for raising this here, but I can't find any other place to discuss.

The SCS modding Wiki (https://modding.scssoft.com/wiki/Documentation/Engine/SDK/Telemetry) is read-only and I can't find a forum thread about the SCS SDK.

Where/how can we raise feature requests for additional data to be exposed by the SCS SDK and, by extension, the SCS SDK plugin.

**Comment by RenCloud** [comment]
As far as i know there is no official place where you can submit requests for the SDK. That's a bit sad. There are a few thinks that would be nice and also wishes from other people.

I don't now if they read/answer stuff in the forum or on other channels about the sdk. 

If there is new stuff that the sdk provides i will update the plugin normally. Other things based on existing information or by other sources (depending on what they need and what they provide) can be requested here as an issue or on the discord server linked in the readme.md file. But for stuff outside the official SDK  i can't promise an integration in the plugin or an solution.

**Comment by mwerle** [comment]
I was thinking about stuff which the game would need to provide.  Such as events for buying garages or hiring drivers etc.  Shame there's no "official" discussion channel for the SDK.

**Comment by N95JPL** [comment]
You could always try [The Forums?](https://forum.scssoft.com/viewforum.php?f=5)

**Comment by mwerle** [comment]
That was my first port of call, but couldn't find any official announcement, or even mention, of the SDK there.  I'm also active in Elite Dangerous and KSP modding, and the devs there announce updates and have discussions about the community SDKs on the official forums (stickied).  So at a bit of a loss that there isn't something similar on the SCS forum..

The few references I found seemed to point at GitHub, and this seems to be the most up-to-date and active repo (which allows commenting).

Guess I can always try to start something ;)
