### ISSUE TITLE
 Image visibility using Boolean

### ISSUE THREAD

**Issue by thommy1972deNeu** [RenCloud/scs-sdk-plugin#69]
I would like to show / hide an image in WPF using a bool. I thought about that:
Brake_Image.Visibility = (data.TruckValues.CurrentValues.MotorValues.BrakeValues.ParkingBrake == true) ? Visibility.Visible : Visibility.Hidden;

Unfortunately, this does not work even though ParkingBrake constantly returns true or false.
Where is my mistake?

The Complete Code: https://pastebin.com/J1advYqR

**Comment by N95JPL** [comment]
Chances are the Image does not have the Build Action set to Resource. If it's anything else, including Embedded Resource, then it will not display properly at runtime.

Other things you can check are the the resolution of the image. In Paint, you'd use File>Properties to view the resolution.

Try saving as a different format, such as jpg. If that works, then it's likely a problem with your file.

You may need to clean and rebuild your solution as well.

**Comment by thommy1972deNeu** [comment]
Viewing the picture is not the problem. However, I would like to switch it on / off with a bool from ParkingBrake

**Comment by N95JPL** [comment]
You can also remove the == true from ".BrakeValues.ParkingBrake == true)", it isn't required

I have just tried: 
`pictureBox1.Visible = data.TruckValues.CurrentValues.MotorValues.BrakeValues.ParkingBrake;`
That has worked perfectly

**Comment by thommy1972deNeu** [comment]
[https://pasteboard.co/J9RP0fy.png](url)

**Comment by N95JPL** [comment]
Are you using a Picture Box? to show the image in WPF?

**Comment by thommy1972deNeu** [comment]
PictureBox is WindowsForms ?

**Comment by N95JPL** [comment]
Oops, so it is! (Apologies)
Have you tried an if rather than the inline? (No idea why that wouldn't be working though..)
if(data.TruckValues.CurrentValues.MotorValues.BrakeValues.ParkingBrake)
{
   Brake_Image.Visibility = Visibility.Visible;
}
else
{
    Brake_Image.Visibility = Visibility.Hidden;
}

**Comment by thommy1972deNeu** [comment]
No change in the overall behavior of the picture :-) the Picture is Visible.

**Comment by N95JPL** [comment]
The link posted above might help...apparently theres a class built in, its written for a button but the principles will be the same

**Comment by RenCloud** [comment]
I also do not use WPF normaly. Did the link helped?

When you switch the Visibility Flag by hand (with a button or so) it works?
