### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by errorflash** [RenCloud/scs-sdk-plugin#76]
Hallo,

kannst du mir sagen wie ich die .dll Dateien erstelle und die Dateien installiere. muss ich die 3 DLL nur in den Plugin ordner kopieren ?

**Comment by RenCloud** [comment]
Hey,

erstellen der .dll erfolgt am einfachsten mit Hilfe von Visual Studio. Wenn du die Solution geöffnet hast (`scs-telemetry/vs2012/scs-telemetry.sln`), dann kannst du das gesamte Projekt oder nur das Projekt `scs-telemetry`  kompilieren. Die .dll die befindet sich dann unter `scs-client\C#\SCSSdkClient\Release`. Solltest du im Debugg Modus kompilieren ist der Ordner `scs-client\C#\SCSSdkClient\Debug`. Dort befindet sich dann die `scs-telemetry.dll` (Selber Name wie im Release Zip). Diese Datei muss in den Ordner `scs-game-dir/bin/win_x64/plugins` (64-bit) kopiert werden. Ab dann sollte beim Spielstart eine Nachricht auftauchen, dass die Telemetry genutzt wird.

Um dann auf die Daten von C# zuzugreifen brauchst du die `SCSSdkClient.dll`. Die kannst du ebenfalls in der vorher geöffneten Solution kompilieren. Danach kann du die .dll in dein Projekt einbinden.

Das Release Zip enthält einmal eine 32bit und 64bit Version der .dll die in den jeweiligen Spiele Plugin Ordner kopiert werden muss. Im Demo Ordner gibts es die Plugin .dll und ein Demo.

**Comment by Cornadius** [comment]
Ich kriege leider jedesmal die Meldung das die Dll nicht erstellt werden kann

**Comment by Cornadius** [comment]
> 
> 
> Hey,
> 
> erstellen der .dll erfolgt am einfachsten mit Hilfe von Visual Studio. Wenn du die Solution geöffnet hast (`scs-telemetry/vs2012/scs-telemetry.sln`), dann kannst du das gesamte Projekt oder nur das Projekt `scs-telemetry` kompilieren. Die .dll die befindet sich dann unter `scs-client\C#\SCSSdkClient\Release`. Solltest du im Debugg Modus kompilieren ist der Ordner `scs-client\C#\SCSSdkClient\Debug`. Dort befindet sich dann die `scs-telemetry.dll` (Selber Name wie im Release Zip). Diese Datei muss in den Ordner `scs-game-dir/bin/win_x64/plugins` (64-bit) kopiert werden. Ab dann sollte beim Spielstart eine Nachricht auftauchen, dass die Telemetry genutzt wird.
> 
> Um dann auf die Daten von C# zuzugreifen brauchst du die `SCSSdkClient.dll`. Die kannst du ebenfalls in der vorher geöffneten Solution kompilieren. Danach kann du die .dll in dein Projekt einbinden.
> 
> Das Release Zip enthält einmal eine 32bit und 64bit Version der .dll die in den jeweiligen Spiele Plugin Ordner kopiert werden muss. Im Demo Ordner gibts es die Plugin .dll und ein Demo.

Ich kriege auch Fehler beim erstellen, kriege keine 32 bit oder 64 bit variante

**Comment by RenCloud** [comment]
Gibt es mehr Informationen die Visual Studio anzeigt?Mit den wenig Informationen kann ich wenig dazu sagen.
