### ISSUE TITLE
Need total driven truck kilometer value of the in-truck display

### ISSUE THREAD

**Issue by Rakinare** [RenCloud/scs-sdk-plugin#77]
Hello,

first of all, thanks a ton for this amazing sdk! It helps a ton. Now I've got a question tho.

I'd like the total driven kilometer value, which I can see in my truck cockpit, to be accesible via the sdk. 
Is this possible to do? Currently it seems to be missing while other stuff like fuel, temperatures and such things are there.

Regards,
Rakinare

**Comment by N95JPL** [comment]
Hello!
Dashboard.Odometer holds this value?

**Comment by Rakinare** [comment]
Ohhh... I am very sorry. The fail here is on my end due to the lack of knowledge of the word "odometer", never heard that before.

Thank you very much!

**Comment by N95JPL** [comment]
Don't say sorry, it's all good!
Happy Trucking!
