### ISSUE TITLE
FinedEvent triggering unreliable? 

### ISSUE THREAD

**Issue by Rakinare** [RenCloud/scs-sdk-plugin#78]
I have been trying to track fines with FinedEvent, however it seems to track extremely unreliable.

Whenever I get a fine triggered ingame such as red light running or speeding I would expect the FinedEvent to be triggered but very often nothing is happening at all. 

Is that a bug with the telemetry or the game itself?

Regards
Rakinare

**Comment by RenCloud** [comment]
Normally it should trigger reliable. You could try to set the update rate higher, but 100ms should be normally enough.

However, I have currently not tested the current game version, but it should work there.

**Comment by Rakinare** [comment]
Thank you very much for your answer!

Oh so that is tied to the update rate too? I though events are always fired when the game sends them and not that the telemetry is observing it. I have set my update rate to 1000ms and it is extremely unreliable. 
So do I have to have a faster update rate there?

**Comment by D3LT4PL** [comment]
Setting update rate to 1000ms makes it slower than default (1000>100ms), try setting it lower, not higher.

**Comment by Rakinare** [comment]
> Setting update rate to 1000ms makes it slower than default (1000>100ms), try setting it lower, not higher.

Yes I know that, I was expecting the events to fire unconditionally to the update rate, like them watching the events fired by the game permanently. I have set my update rate to 1000ms, cause a lower update rate was messing with my software.

**Comment by RenCloud** [comment]
The game will fire it at the right moment, but the C# plugin only periodically updates the data. So if the refresh rate is to low most of the events will be lost.

However you can make changes to the c++ code, if you have no other choice. Than the low refresh rate would work.

**Comment by RenCloud** [comment]
Should be fixed. Events should be refresh rate independent (at least in that way, that as long no new event is called between the refresh time it should work reliable)
