### ISSUE TITLE
Missing body damage value for trailers

### ISSUE THREAD

**Issue by kniffen** [RenCloud/scs-sdk-plugin#86]
The trailer damage values are missing the trailer's body damage, as such it's not possible to know the total damage of the trailer.

*Edit*
On further inspection it looks like it's the SCS SDK that is is missing this value, so probably nothing that can be done about it.... for now.

**Comment by RenCloud** [comment]
Yes seems to be missing. I close this issue. When there is a new sdk version with this value i will add it.
