### ISSUE TITLE
Freight Names

### ISSUE THREAD

**Issue by thommy1972deNeu** [RenCloud/scs-sdk-plugin#92]
For some time now, my charges and locations in the C # code have been in English, but are being transmitted in German.
I am in the client, for example. "medvaccine" is displayed as a load, but "Medizinische Impfstoffe" is entered in the database. As a value I use 
-> JobValues/CargoValues/Name
Does anyone else have this phenomenon?

**Comment by Pnaop** [comment]
The value you're getting currently is a translated String. I suspect you're playing in German? If you were to change the language to English this value would change to the English language.

I think you are looking for the value -> JobValues/CargoValues/Id, that would give you the "medvaccine" 'code'

**Comment by thommy1972de** [comment]
I am aware of that, it also went on for 1-2 years, so I was surprised that it is no longer possible :-)
It is also entered in German in the database that is the strange thing. I'll test the values

**Comment by RenCloud** [comment]
Based on the SDK comments in the header the language is the in-game language for most of the values e.g. for the cargo name the comment says
> Name of the cargo for display purposes.
> Localized using the current in-game language.

To handle the same stuff in multiple languages, there is the `ID` field. For the Cargo ID the comments says
> Id of the cargo for internal use by code.
> Limited to C-identifier characters and dots.
