### ISSUE TITLE
JobFinish Event on SCS Convoi Mode

### ISSUE THREAD

**Issue by thommy1972de** [RenCloud/scs-sdk-plugin#93]
the jobfinish event does not work in my scs convoy mode.  could it be that scs added a new event when exiting the convoy?

**Comment by ndelta0** [comment]
SCS didn't add anything job-related in the last update IIRC, it's either a bug with the plugin or the game.

**Comment by RenCloud** [comment]
Just tested it in a single person convoy. For me the event was called. When this still happens, could you please check if that happens for all on all except the hosting user. 
May also based on who finished first or other things.

**Comment by TrucksLOG** [comment]
Everything works for the first user, I think it doesn't work for everyone who accepts the job of the first user.  I'll test again this afternoon

**Comment by RenCloud** [comment]
Thanks for the information. 

Sadly, this sound more like a problem of the game.

In some cases, changes to the telemetry code could fix that probably, but currently I see no complete fix for that.
