### ISSUE TITLE
jobFinished and jobCancelled event triggered both on delivery

### ISSUE THREAD

**Issue by MisteryMan** [RenCloud/scs-sdk-plugin#94]
I'm using JAGfx dashboard which utilizes your SDK plugin. On each delivery both events are triggered. Which shouldn't happen. Happened twice. I also use a Tracker for the VTC I belong to, and it also uses the same SDK, and it also registered both events. In the tracker this presents the issue that jobs cannot be verified because it treats the last event which is jobCancelled.

Tested on 2 separate trips and both trips were standard non-WoT contracts on TMP.

Both cases it was v.1.11

**Comment by RenCloud** [comment]
For normal deliveries i could not reproduce that behavior. 

When the other tool also call both it seems to be a problem with the multiplayer. Both events are basically just forwarded from the game.


Is this still happening?

**Comment by chunkbanned** [comment]
I have the same issue
https://i.e-z.host/c3yszt9h.png

**Comment by RenCloud** [comment]
Did it happen in Singleplayer or like above with tmp

**Comment by chunkbanned** [comment]
> I have the same issue https://i.e-z.host/c3yszt9h.png

I managed to fix my issue, nothing to do with the SDK itself, but the way I was detecting users coming on and off jobs.
