### ISSUE TITLE
Tour implementing

### ISSUE THREAD

**Issue by TrucksLOG** [RenCloud/scs-sdk-plugin#97]
has less to do with the telemetry now, but a few clever people seem to be reading mi here.  does anyone have experience with implementing their own tour?  If so, could you please write to me pm, I have 2-3 questions (German/English)

**Comment by ndelta0** [comment]
What do you mean by "tour"? Also, how is it related to the plugin?

**Comment by TrucksLOG** [comment]
Not in the telemetry, in the game.sii
