### ISSUE TITLE
Daily mileage and other parameters ?

### ISSUE THREAD

**Issue by NazarDiadiun** [RenCloud/scs-sdk-plugin#99]
Hello to all!

Is it possible to get a daily mileage, or is it only possible if SCS releases such a possibility in their SDK?
The same question, for example, to the ambient temperature.

I connect the dashboard from DAF XF, I would like to fully implement the functionality :)

**Comment by ndelta0** [comment]
To be honest, this seems to be outside of the scope of the plugin. Its job is only to relay the data from the game to the other applications. It already relays all of the available data, so if it's not there, it's not readable by the plugin.

Since you want to have an IRL dashboard, you'll most probably use some kind of a microcontroller. Some of them (like Arduinos and their AT microcontrollers) have a built-in EEPROM, which you could use to store the data and calculate it on the fly.

**Comment by ndelta0** [comment]
> So you think it’s a good idea to reset the mileage in the game and the dashboard and then store the differences in mileage in microcontroller memory?

For me that seems to be the only option, since the AVG fuel usage is not available to the telemetry.

**Comment by N95JPL** [comment]
To jump in on this, when I release the new version of SCS-Telemetry-Server I might actually include these as optional parameters... 
Calculating daily mileage also depends on what you count as daily?
Per driving day? Per full 24 hours?

Also isn't Average Consumption already a part of the SDK?

**Comment by NazarDiadiun** [comment]
By daily mileage, I mean mileage, which is under total mileage. Which is manually resetting on the dashboard by button

**Comment by ndelta0** [comment]
So you're talking about the odometer?

**Comment by NazarDiadiun** [comment]
Yes, but there is an odometer that displays a total mileage, for example, 180,000 km, and there is a separate so-called daily mileage that can be dropped

**Comment by N95JPL** [comment]
Also known as a "Trip Mileage" for British folks?
Resets to 0 then counts per trip... example my car had the odometer then
- Trip 1: Resets when Car doesn't move for > 1 Hour
- Trip 2: Resets when commanded via button

Is this what you mean?

**Comment by NazarDiadiun** [comment]
Yes, it is. I didn’t know, by the way, that it would reset itself if the car didn’t move for an hour or more

**Comment by ndelta0** [comment]
> I didn’t know, by the way, that it would reset itself if the car didn’t move for an hour or more

It probably depends on the car, I only saw cars with Trip A and Trip B, both of which were manually resettable.

**Comment by N95JPL** [comment]
> Yes, it is. I didn’t know, by the way, that it would reset itself if the car didn’t move for an hour or more

It depends on the car, some do, some don't i was just referencing my own car as an example

**Comment by NazarDiadiun** [comment]
Yes, I found a CAN address that shows when the reset button is pressed. I’ll store this mileage in EEPROM, once just synchronize with the game. It would, of course, be cool if my ATmega32u4 could work with the serial port and as a HID device at the same time. Then I could press a button on the panel and reset mileage in the game. 
In any case, it would be great if the SCS added more data to the telemetry. The extra data will never be :)

**Comment by N95JPL** [comment]
> Yes, I found a CAN address that shows when the reset button is pressed. I’ll store this mileage in EEPROM, once just synchronize with the game. It would, of course, be cool if my ATmega32u4 could work with the serial port and as a HID device at the same time. Then I could press a button on the panel and reset mileage in the game. 
> 
> In any case, it would be great if the SCS added more data to the telemetry. The extra data will never be :)

If there's a button for it, why don't you get the ATmega32u4 to send a message back through the serial to the system that's brokering the telemetry messages (how are you doing that btw)
I can't remember but does the ingame dash show trip miles? If so I never realised they were resettable?
If they are, map a key to do it then the Telemetry Broker could emulate that keystroke?

**Comment by NazarDiadiun** [comment]
Damn, really! 

I use telemetry server, and through simple python script parsing JSON document on URL request. 
Indeed, why not make the python script listen to the serial port, and simply imitate button press. 

Yes, Euro Truck Simulator 2 has a daily mileage, and you can also reset it. 

Thank you for such cool ideas :)

**Comment by N95JPL** [comment]
No problem!
You'll have to show us your setup! I am really curious!

**Comment by NazarDiadiun** [comment]
It’s sad that not many people do that, or don’t want to share their projects. I plan to upload all my work into the public repository. I have already created a repository, I will soon publish part of the results of my work :)

https://github.com/NazarDiadiun/ETS2-DAF-Dashboard

**Comment by RenCloud** [comment]
So far I see there is no further question here? If not, just reopen the issue. 

If some new questions came up, feel free to open another issue or if it's less related to the plugin, you may also can join the discord server. Currently, there is not a specific channel for that specific talk, but I think about changing that, due to some action lately.

Your project sound nice. Thanks for sharing.
